# Generated by Django 3.0.8 on 2020-07-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20200703_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fotos',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
