# Generated by Django 3.0.8 on 2020-07-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fotos',
            field=models.ImageField(upload_to='clientes_fotos'),
        ),
    ]
